# @package _global_
# PGD-EOT attack configuration for CIFAR-10 randomized smoothing defense (HuggingFace ViT).

defaults:
  - /base/defaults@_global_
  - /models/vit_p16_224@_global_
  - override /hydra/launcher: submitit_slurm_cifar10
  - _self_

sample_size: 1750 #1722 real samples
#random_seed: 42
sample_correct_predictions: true
sample_stratified: false

sigma: 0.25
N0: 100
N: 100000
batch_size: 200
alpha: 0.001

split: "test"
dataset_name: "CIFAR-10"

classifier_type: "huggingface"
classifier_name: "aaraki/vit-base-patch16-224-in21k-finetuned-cifar10"
experiment_tag: "pgd_eot_attack_cifar10_vit_p16_224"

attack:
  targeted: false

  norm: "l2"
  random_start: true
  bounds: null

  attack_only_if_correct: true

  sigma: 0.25
  cert_N0: 100
  cert_N: 100000
  cert_alpha: 0.001
  cert_batch_size: 200

  # Smoothed prediction at x_adv for success criterion
  eval_alpha: 0.001
  log_every: 10

  # Also estimate the minimum L2 radius where an adversarial exists (may be outside certified radius).
  min_radius_search:
    epsilon_start: 0.0
    epsilon_stop: 4.0
    epsilon_step: 0.05
    restarts: 1

  # Load a previous certify run (must match sigma + classifier). Disabled by default for this template.
  certify_run:
    enabled: false
    path: /gpfs/work2/0/prjs1681/runs/results/CIFAR-10/certification_cifar_10_vit_base_patch16_224_in21k_finetuned_cifar10_20260101_205741_796722
    sigma_tol: 1e-6

