# Base configuration for ImageNet experiments
# @package _global_

dataset_name: "ImageNet"
split: "test"

# Sampling configuration
sample_size: 100
random_seed: 42
sample_stratified: false

# Certification parameters
sigma: 0.25
N0: 100
N: 10000
batch_size: 200
alpha: 0.001
sample_correct_predictions: true

# Classifier configuration
classifier_type: "timm"
classifier_name: "beit_large_patch16_512"

# Experiment configuration
mode: certify

hydra:
  job:
    name: certify_${dataset_name}_${sigma}_${sample_size}
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset_name}_sigma_${sigma}_size_${sample_size}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: sigma_${sigma}_size_${sample_size}

