_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

submitit_folder: ${hydra.sweep.dir}/.submitit/${now:%Y-%m-%d_%H-%M-%S}


partition: gpu_a100
gpus_per_node: 1
cpus_per_task: 18
mem_gb: 120
timeout_min: 1200


name: certify_${hydra.job.name}
comment: "Hydra certification sweep"


additional_parameters: {}

setup:
  - source /gpfs/home2/jvrijn/miniforge3/etc/profile.d/conda.sh
  - conda activate verona_new
  - cd /home/jvrijn/code/rs/verif/VERONA_rs_rd/rs_rd/randomized_smoothing/cifar10