# Hydra config file for certify.py
# Usage: 
#   Single run: python certify.py
#   Override: python certify.py sigma=0.5 sample_size=200
#   Sweep: python certify.py -m sigma=0.25,0.5,0.75 sample_size=100,200

# Dataset configuration
dataset_name: "CIFAR-10"
split: "test"

# Sampling configuration
sample_size: 100
random_seed: 42
stratified: true

# Certification parameters
sigma: 0.25
N0: 100
N: 100000
batch_size: 1000
alpha: 0.001
sample_correct_predictions: true

# Classifier configuration
classifier_type: "huggingface"
classifier_name: "aaraki/vit-base-patch16-224-in21k-finetuned-cifar10"

# Experiment configuration
experiment_type: "certification"

# Hydra configuration
defaults:
  - hydra/launcher: submitit_slurm  # Use SLURM launcher for sweeps
  - hydra/sweeper: basic  # Basic sweeper for parameter grids

hydra:
  job:
    name: certify_${dataset_name}_${sigma}_${sample_size}
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset_name}_sigma_${sigma}_size_${sample_size}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: sigma_${sigma}_size_${sample_size}
