# Default configuration parameters for CIFAR-10 certification experiments

# Basic experiment configuration
experiment_type: "certification"
dataset_name: "CIFAR-10"
split: "test"

# Sampling configuration
sample_size: 10
random_seed: 42
sample_correct_predictions: true
sample_stratified: false

mode: "predict"

# Randomized smoothing variables
sigma: 0.25
N0: 100
N: 100000
batch_size: 200
alpha: 0.001

# Classifier configuration
classifier_type: "pytorch"
classifier_name: "cifar10_convlarge"
pytorch_normalization: "sdpcrown"
#experiment tracking
experiment_tag: "predict_check"
