# Default configuration parameters for CIFAR-10 certification experiments

# Basic experiment configuration
experiment_type: "certification"
dataset_name: "CIFAR-10"
split: "test"

# Sampling configuration
sample_size: 100
random_seed: 42
sample_correct_predictions: true
sample_stratified: false

# Randomized smoothing variables
sigma: 0.25
N0: 100
N: 100000
batch_size: 200
alpha: 0.001

# Classifier configuration
classifier_type: "huggingface"
classifier_name: "aaraki/vit-base-patch16-224-in21k-finetuned-cifar10"

#experiment tracking
experiment_tag: "default"
