# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm_imagenet
  - _self_

data_dir: ${oc.env:PRJS}/datasets/ImageNet/train


output_path: ${oc.env:PRJS}/models/ImageNet/SiT/LoRA/sit_lora_sigma0p25.pt


sit_model_name: SiT-XL/2
sit_checkpoint_path: ${oc.env:PRJS}/models/ImageNet/SiT/SiT-XL-2-256x256.pt
sit_vae_id: stabilityai/sd-vae-ft-mse

image_size: 256
batch_size: 32
num_workers: 8
lr: 1e-4
weight_decay: 0.0
max_steps: 30000
log_every: 50
save_every: 1000

sigma: 0.25
diffusion_steps: 1000
noise_schedule: linear
tau_k: 1.0

amp_dtype: bf16

lora_r: 16 
lora_alpha: 32.0
lora_dropout: 0.0
lora_targets: [qkv, proj, fc1, fc2]

